name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    # Hier w체rden die Schritte f체r das Deployment folgen
    # Dies ist nur ein Platzhalter, da das tats채chliche Deployment 
    # von Ihrer spezifischen Hosting-Umgebung abh채ngt
    
    # - name: Deploy to Production
    #   run: |
    #     # Deployment-Schritte hier
